# Generated by Django 5.2.17 on 2026-08-30 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(max_length=64, unique=True, verbose_name="token"),
                ),
                ("tool", models.CharField(max_length=64, verbose_name="tool")),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="parameters"),
                ),
                ("question", models.CharField(max_length=255, verbose_name="question")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("low_confidence", "Sokoni was unsure what it heard"),
                            ("unusual_amount", "The amount is unlike this business"),
                            ("new_party", "Nobody by that name has traded here before"),
                        ],
                        max_length=32,
                        verbose_name="reason",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, null=True, verbose_name="confidence"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="consumed at"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to="businesses.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pending action",
                "verbose_name_plural": "pending actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="agent_pendi_token_d4a45a_idx")
                ],
            },
        ),
    ]
