# Generated by Django 5.2.17 on 2026-08-30 19:03

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("supplier", "Supplier"),
                            ("both", "Customer and supplier"),
                        ],
                        default="customer",
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number, e.g. +254712345678.",
                                regex="^\\+?[0-9]{7,15}$",
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "party",
                "verbose_name_plural": "parties",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("business"),
                        name="unique_party_name_per_business",
                    )
                ],
            },
        ),
    ]
