from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.core.constants import (
    DEFAULT_CURRENCY,
    MONEY_DECIMAL_PLACES,
    MONEY_MAX_DIGITS,
)
from apps.core.models import BusinessScopedModel


class TransactionType(models.TextChoices):
    SALE = "sale", _("Sale")
    INCOME = "income", _("Other income")
    PURCHASE = "purchase", _("Stock purchase")
    EXPENSE = "expense", _("Expense")


#: Types that bring money into the business, and those that take it out.
MONEY_IN_TYPES = {TransactionType.SALE, TransactionType.INCOME}
MONEY_OUT_TYPES = {TransactionType.PURCHASE, TransactionType.EXPENSE}


class PaymentStatus(models.TextChoices):
    PAID = "paid", _("Paid in full")
    PARTIAL = "partial", _("Partially paid")
    CREDIT = "credit", _("Unpaid (on credit)")


class PaymentMethod(models.TextChoices):
    CASH = "cash", _("Cash")
    MPESA = "mpesa", _("M-Pesa")
    BANK = "bank", _("Bank")
    CREDIT = "credit", _("On credit")
    OTHER = "other", _("Other")


class TransactionSource(models.TextChoices):
    """
    How the record entered the system.

    This drives the academic evaluation comparing voice entry against form
    entry, so it is recorded on every transaction rather than inferred later.
    """

    MANUAL = "manual", _("Entered manually")
    VOICE = "voice", _("Spoken to Sokoni")
    IMPORT = "import", _("Imported")
    API = "api", _("Created through the API")
    SYSTEM = "system", _("Generated by Sokoni")
    MPESA = "mpesa", _("Reconciled from M-Pesa")


class TransactionQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def money_in(self):
        return self.filter(transaction_type__in=MONEY_IN_TYPES)

    def money_out(self):
        return self.filter(transaction_type__in=MONEY_OUT_TYPES)

    def unsettled(self):
        """Transactions with money still owed in either direction."""
        return self.filter(
            payment_status__in=[PaymentStatus.CREDIT, PaymentStatus.PARTIAL]
        )

    def in_period(self, start=None, end=None):
        queryset = self
        if start is not None:
            queryset = queryset.filter(occurred_at__gte=start)
        if end is not None:
            queryset = queryset.filter(occurred_at__lte=end)
        return queryset


class Transaction(BusinessScopedModel):
    """
    A single business event involving money.

    Sokoni records what happened rather than debits and credits: a sale, a
    purchase, an expense, other income. Full double-entry would add rigour this
    user base does not need and a vocabulary they do not use, so consistency is
    enforced through validation instead.
    """

    transaction_type = models.CharField(
        _("type"), max_length=16, choices=TransactionType.choices
    )
    amount = models.DecimalField(
        _("amount"),
        max_digits=MONEY_MAX_DIGITS,
        decimal_places=MONEY_DECIMAL_PLACES,
        validators=[MinValueValidator(Decimal("0.01"))],
    )
    amount_paid = models.DecimalField(
        _("amount settled"),
        max_digits=MONEY_MAX_DIGITS,
        decimal_places=MONEY_DECIMAL_PLACES,
        default=Decimal("0.00"),
        validators=[MinValueValidator(Decimal("0.00"))],
        help_text=_("How much of the amount has actually changed hands."),
    )
    currency = models.CharField(_("currency"), max_length=3, default=DEFAULT_CURRENCY)

    payment_status = models.CharField(
        _("payment status"),
        max_length=16,
        choices=PaymentStatus.choices,
        default=PaymentStatus.PAID,
    )
    payment_method = models.CharField(
        _("payment method"),
        max_length=16,
        choices=PaymentMethod.choices,
        default=PaymentMethod.CASH,
    )

    occurred_at = models.DateTimeField(_("occurred at"), default=timezone.now)
    description = models.CharField(_("description"), max_length=255, blank=True)
    notes = models.TextField(_("notes"), blank=True)

    party = models.ForeignKey(
        "parties.Party",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="transactions",
    )
    product = models.ForeignKey(
        "catalog.Product",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="transactions",
    )
    quantity = models.DecimalField(
        _("quantity"),
        max_digits=12,
        decimal_places=3,
        null=True,
        blank=True,
        validators=[MinValueValidator(Decimal("0.001"))],
    )
    unit_price = models.DecimalField(
        _("unit price"),
        max_digits=MONEY_MAX_DIGITS,
        decimal_places=MONEY_DECIMAL_PLACES,
        null=True,
        blank=True,
        validators=[MinValueValidator(Decimal("0.00"))],
    )

    source = models.CharField(
        _("source"),
        max_length=16,
        choices=TransactionSource.choices,
        default=TransactionSource.MANUAL,
    )
    reference = models.CharField(
        _("reference"),
        max_length=64,
        blank=True,
        help_text=_("External identifier, such as an M-Pesa confirmation code."),
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="transactions_created",
    )

    objects = TransactionQuerySet.as_manager()

    class Meta:
        verbose_name = _("transaction")
        verbose_name_plural = _("transactions")
        ordering = ["-occurred_at", "-created_at"]
        indexes = [
            models.Index(fields=["business", "-occurred_at"]),
            models.Index(fields=["business", "transaction_type"]),
            models.Index(fields=["business", "payment_status"]),
        ]

    def __str__(self):
        return f"{self.get_transaction_type_display()} {self.currency} {self.amount}"

    @property
    def is_money_in(self):
        return self.transaction_type in MONEY_IN_TYPES

    @property
    def signed_amount(self) -> Decimal:
        """Positive when money enters the business, negative when it leaves."""
        return self.amount if self.is_money_in else -self.amount

    @property
    def settled_amount(self) -> Decimal:
        """The cash that actually moved, signed like `signed_amount`."""
        return self.amount_paid if self.is_money_in else -self.amount_paid

    @property
    def outstanding_amount(self) -> Decimal:
        """What still has to be settled. Becomes a debt in a later phase."""
        return self.amount - self.amount_paid
