# Generated by Django 5.2.17 on 2026-08-30 23:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="recorded at"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("paid", "Payment recorded"),
                            ("written_off", "Written off"),
                            ("archived", "Archived"),
                        ],
                        max_length=16,
                        verbose_name="action",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("transaction", "Transaction"),
                            ("debt", "Debt"),
                            ("debt_payment", "Debt payment"),
                        ],
                        max_length=16,
                        verbose_name="object type",
                    ),
                ),
                ("object_id", models.UUIDField(verbose_name="object id")),
                ("summary", models.CharField(max_length=255, verbose_name="summary")),
                (
                    "before",
                    models.JSONField(blank=True, null=True, verbose_name="before"),
                ),
                (
                    "after",
                    models.JSONField(blank=True, null=True, verbose_name="after"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=16, verbose_name="source"),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="extra"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-created_at"],
                        name="audit_audit_busines_19e579_idx",
                    ),
                    models.Index(
                        fields=["business", "object_type", "object_id"],
                        name="audit_audit_busines_50ec2c_idx",
                    ),
                ],
            },
        ),
    ]
