# Generated by Django 5.2.17 on 2026-08-30 19:03

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="How it is counted, e.g. crate, kg, piece, gunia.",
                        max_length=32,
                        verbose_name="unit",
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional. Used as a suggestion, never as a fixed rate.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="usual price",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("business"),
                        name="unique_product_name_per_business",
                    )
                ],
            },
        ),
    ]
