# Generated by Django 5.2.17 on 2026-08-30 19:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("catalog", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("income", "Other income"),
                            ("purchase", "Stock purchase"),
                            ("expense", "Expense"),
                        ],
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="How much of the amount has actually changed hands.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="amount settled",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KES", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid in full"),
                            ("partial", "Partially paid"),
                            ("credit", "Unpaid (on credit)"),
                        ],
                        default="paid",
                        max_length=16,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("bank", "Bank"),
                            ("credit", "On credit"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=16,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="occurred at"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="unit price",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered manually"),
                            ("voice", "Spoken to Sokoni"),
                            ("import", "Imported"),
                            ("api", "Created through the API"),
                            ("system", "Generated by Sokoni"),
                            ("mpesa", "Reconciled from M-Pesa"),
                        ],
                        default="manual",
                        max_length=16,
                        verbose_name="source",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="External identifier, such as an M-Pesa confirmation code.",
                        max_length=64,
                        verbose_name="reference",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="parties.party",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "-occurred_at"],
                        name="ledger_tran_busines_a8bd0d_idx",
                    ),
                    models.Index(
                        fields=["business", "transaction_type"],
                        name="ledger_tran_busines_4b3695_idx",
                    ),
                    models.Index(
                        fields=["business", "payment_status"],
                        name="ledger_tran_busines_1cd48f_idx",
                    ),
                ],
            },
        ),
    ]
