# Generated by Django 5.2.17 on 2026-08-30 21:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("ledger", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("receivable", "Owed to the business"),
                            ("payable", "Owed by the business"),
                        ],
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="original amount",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KES", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Nothing paid yet"),
                            ("partial", "Partly paid"),
                            ("settled", "Fully paid"),
                            ("written_off", "Written off"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered manually"),
                            ("voice", "Spoken to Sokoni"),
                            ("import", "Imported"),
                            ("api", "Created through the API"),
                            ("system", "Generated by Sokoni"),
                            ("mpesa", "Reconciled from M-Pesa"),
                        ],
                        default="manual",
                        max_length=16,
                        verbose_name="source",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="A debt always belongs to someone.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debts",
                        to="parties.party",
                    ),
                ),
                (
                    "source_transaction",
                    models.OneToOneField(
                        blank=True,
                        help_text="The credit sale or purchase this debt came from, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debt",
                        to="ledger.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "debt",
                "verbose_name_plural": "debts",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DebtPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="paid at"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("bank", "Bank"),
                            ("credit", "On credit"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=16,
                        verbose_name="payment method",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered manually"),
                            ("voice", "Spoken to Sokoni"),
                            ("import", "Imported"),
                            ("api", "Created through the API"),
                            ("system", "Generated by Sokoni"),
                            ("mpesa", "Reconciled from M-Pesa"),
                        ],
                        default="manual",
                        max_length=16,
                        verbose_name="source",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debt_payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="debts.debt",
                    ),
                ),
            ],
            options={
                "verbose_name": "debt payment",
                "verbose_name_plural": "debt payments",
                "ordering": ["-paid_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["business", "debt_type", "status"],
                name="debts_debt_busines_1cffca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["business", "due_date"], name="debts_debt_busines_2806dd_idx"
            ),
        ),
    ]
